---
collections:
  # install collection from ansible galaxy.
  - name: community.general
    source: https://galaxy.ansible.com/
    version: 6.4.0
  # install collection from ansible galaxy.
  - name: oracle.oci
    source: https://galaxy.ansible.com/
    version: 4.10.0
